version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - FLASK_ENV=development
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge